name: deploy-api

on:
  push:
    branches:
      - main
      - dev
      - staging

    # paths:
    #   - 'src/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Tests
        run: echo "(incoming)"

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
       
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: dufourchri
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: dufourchri/suno-bark
          context: .
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
